### PR TITLE
Add sign isos

### PR DESCRIPTION
**Pull request by Ste74**
@artoo can you add this to sign the isos in a second time ? I don't know if necessary change the name of the script ( for me this is not a problem )

### CODE REVIEW

**Comment by udeved** [comment]
The plan was @Ste74 to implement signing of the sfs images, similar to how checksum is done in initramfs.
The code already exists, I just haven't made a decision how and where we get the key from.

See here:
https://github.com/manjaro/manjaro-tools/blob/master/lib/util-iso.sh#L355

here:
https://github.com/manjaro/manjaro-tools/blob/master/initcpio/hooks/miso#L177

So it would work like this at iso kernel arg input field by adding **verify** or **verify=y**

**Comment by Ste74** [comment]
Oh great :) .... In this case if you require the key during the build iso we need to increase the time of the sign remain in the cache .. when you start the build mt ask the psw to sign the iso .. build an iso in my pc require 30/40 minutes so the psw no elapse in this time : 
i mean this 
max-cache-ttl 3600
in gpg-agent.conf file .. or not ?

**Comment by udeved** [comment]
I can't say currently about ttl @Ste74 We'll see. :)
signing would take place after checksum creation, for each sfs image present.

Easiest way to get key is from makepkg.conf, but it feels strange to use pkg config file for iso.

**Comment by Ste74** [comment]
@philmmanjaro  yep i agree .. close this 😄

**Pull request closed without merging**
