### PR TITLE
actual_branch() for ISO-name

### PR DESCRIPTION
**Pull request by oberon2007**
I know, you ain't gonna merge this anyway :laughing: 
So, just for fun and to show how simple an addition (and improvement in my eyes) it would have been :)

### CODE REVIEW

**Comment by udeved** [comment]
I am against nannying the user, especially if the user is a developer or maintainer.
He got to take responsibility and to know what he is doing.
Its a philosophical issue here.

**Comment by udeved** [comment]
I am almost certain this change would create problems fwith filename, if the chroot wasn't cleaned and another image only run was to follow. The result would be a wrong branch in filename, it would use the previous branch.

**Comment by oberon2007** [comment]
My thinking was that actual_branch() will only be called during the squashing, so the correct branch would necessarily be present in the chroot's pacman-mirrors.conf, or else the config in the ISO itself would be wrong...

**Comment by oberon2007** [comment]
In a case it doesn't seems ideal to me that the filename should depend on an arg being passed rather than the actual content of the file.

**Comment by udeved** [comment]
Keep it simple, your request would add only unnecessary layer of complexity and we'd need additional checks.
Input parameters are input parameters.
I still don't get why you don't set it in your user config, and be done with it. No arg specification this way.

**Comment by oberon2007** [comment]
It's fine. No big deal

**Pull request closed without merging**
