### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by udeved**
version 0.9.10
-several fixes
-manjaro-chroot automount

### CODE REVIEW

**Comment by philmmanjaro** [comment]
from my end I see no issues to not merge this one and release **0.9.10** seems to be a good version, which brings a lot of needed fixes.

**Comment by udeved** [comment]
Are we going to put 0.9.10 in all branches at once?
I was going to remove the compat symlink of Packages-Custom(its now shared/Packages-Desktop)

If we do all branches, I would tend to change the Packages-Xorg in Packages-Drivers.
Reason, I think Packages-Xorg can be misleading to the user, as he may thinks this file contains xorg, when in fact, it contains drivers only for the drivers repo on iso.
I have never tried, but what happens if one puts xorg-server in that Packages-Xorg? Will it be installed?

**Comment by Kirek** [comment]
Actually Packages-Mhwd would be more accurate, as they are the extra packages that mhwd needs to be able to install mhwd-configs in the livecd.

In other words if you parsed all MHWD config for all the packages that every config needs, that would create the actual Packages-Xorg file.

Having more stuff than that would be a waste of space in the iso.

**Comment by udeved** [comment]
Speaking of MHWDCONFIG files.
The bumblebee-nvidia makes problems on openrc due to primus in depends array, which is already depend of bumblebee or bumblebee-openrc.
However, if I change MHWDCONFIG, pacman fails due to inablity to remove packages.
I guess pacman would have to be called with --noconfirm to solve this.

Anyway, I am also fine with Packages-Mhwd

**Comment by philmmanjaro** [comment]
I merge **unstable** with **testing** and push all on Monday to **stable** anyway ...
Btw. f47e96b made it now un-mergable ;)

**Comment by philmmanjaro** [comment]
**bumblebee-nvidia** profile normally works as is. At least on **systemd**. **bumblebee-openrc** might need adjustment then. Else we have to look into **mhwd** itself.

**Pull request merged**
