### PR TITLE
Add PXE support

### PR DESCRIPTION
**Pull request by philmmanjaro**
How to add PXE support to Manjaro builds:

1) we need curl then 
1.1) the file
/usr/lib/initcpio/install/net
should add the line
```
    add_binary "/usr/lib/initcpio/curl"  "/bin/curl"
```
1.2) copy /bin/curl to /usr/lib/initcpio/

2) mkinitcpio-net.conf should contain
```
    HOOKS="base udev net miso miso_pxe_common miso_pxe_http miso_pxe_nbd miso_loop_mnt miso_kms modconf block pcmcia filesystems keyboard keymap plymouth"
    COMPRESSION="xz"
```

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Regardless the given description we might need to add **mkinitcpio-nfs-utils** to our profiles.

**Comment by udeved** [comment]
How are we going to deal with changes mkinitcpio.conf in the profiles?
Do we make it default?
I just ask so we can adapt the uefi partition size that it won't throw an error..

**Comment by philmmanjaro** [comment]
Let me check some stuff first. I've to make my mind up to this one ... Seems to be a little complex ...

**Comment by philmmanjaro** [comment]
Do we need [udev/rules.d/81-dhcpcd.rules](https://projects.archlinux.org/archiso.git/tree/configs/releng/airootfs/etc/udev/rules.d/81-dhcpcd.rules) ?!?

**Comment by ppatpat** [comment]
no you don't

**Pull request merged**
