### PR TITLE
introduce separate vars target_branch_iso and target_branch_pkg

### PR DESCRIPTION
**Pull request by oberon2007**
Just a suggestion:
Although we already have option ``-b`` available, at times like now when we are building testing and stable ISOs and at the same time continue building packages against unstable, I think it is very convenient to be able to set ``target_branch`` separately for ISOs and pkgs in **manjaro-tools.conf**.

### CODE REVIEW

**Comment by udeved** [comment]
I don't like the idea.
0.14 already got rid of settings, I don't want to reintroduce new settings.
-b switch is perfectly fine, my setting defaults to unstable..

**Comment by philmmanjaro** [comment]
I'm fine with adding **signiso** and having **trackfile**. Having **dist_codename** configurable we have to talk about. As we define it, it should be enough and not needed to be modified by the user. Only makes sense to do so for custom builds. However making **netgroups** configurable might create some issues with code quality of those. Why is that needed?

The current **-b switch** setting is enough. Introducing another set of settings is overkill.

**Comment by oberon2007** [comment]
It shouldn't all get in this PR, sorry. That was an accident. It was supposed to be only the suggestion about target branch. I use configurable dist_codename for myself right now because it will be set to Fringilla still on stable branch as long as manjaro-release pkg isn't changed. Configurable netgroups was fur my experiments with cinnamon-hybrid. My branches got mixed up... Closing this.

**Comment by udeved** [comment]
manjaro-release-dev installled on the build system will take care of setting proper lsb.
I removed settings, the removed ones now all initialize from lsb-release or os-release file.

Netgroups repo follows $profile/*.yaml, add folder with data yaml there for other profiles.

Development scripts/tools are no convenience project for lazy people, its why the -b switch is enough. :)
Reason to remove settings was to simplify the conf file, we had accumulated settings which are not necessary.

**Comment by oberon2007** [comment]
Aah, I wasn't aware of the release-dev package! Thanks.

**Pull request closed without merging**
