### PR TITLE
avoid xdg-open loop in i3 and fluxbox

### PR DESCRIPTION
**Pull request by oberon2007**

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Die Einreihung ist falsch. Schau dir mal Zeile 380 an ...

**Comment by oberon2007** [comment]
Ähm, ich glaub ich verstehs nicht.
Ich möchte einfach dass **configure_env()** im Fall von i3 oder fluxbox **nichts** tut, und das erreicht es auch so. Aber richtet es jetzt was anderes an, ich seh es nicht... Sorry ;)

**Comment by philmmanjaro** [comment]
Dein Code:
```
  configure_env(){
	# avoid xdg-open loop in i3 and fluxbox
	if [ ! -e "/usr/bin/i3" ] && [ ! -e "/usr/bin/fluxbox" ] ; then
 	echo "BROWSER=/usr/bin/xdg-open" >> /etc/environment
 	echo "BROWSER=/usr/bin/xdg-open" >> /etc/skel/.bashrc
 	echo "BROWSER=/usr/bin/xdg-open" >> /etc/profile
	fi
```

Korregierter Code:

```
  configure_env(){
	# avoid xdg-open loop in i3 and fluxbox
	if [ ! -e "/usr/bin/i3" ] && [ ! -e "/usr/bin/fluxbox" ] ; then
 		echo "BROWSER=/usr/bin/xdg-open" >> /etc/environment
 		echo "BROWSER=/usr/bin/xdg-open" >> /etc/skel/.bashrc
 		echo "BROWSER=/usr/bin/xdg-open" >> /etc/profile
	fi
```
sprich die Einreihung war falsch ...

**Comment by philmmanjaro** [comment]
... müsste dann halt auch in den andern Projekten geändert werden ...

**Comment by oberon2007** [comment]
Ah, ja klar. Ist korrigiert.
Should be fixed for other minimal desktops, too, yes. But maintainers will have to export the proper BROWSER variable corresponding to their browser of choice from their **skel/.bashrc** @holmeslinux , @Chrysostomus ...

**Comment by philmmanjaro** [comment]
Well, we can also add an option to the config file and adopt that setting then. Default can be then the given **/usr/bin/xdg-open**, which will be then reused by Calamares and Thus.

**Comment by oberon2007** [comment]
Which config file do you mean? **profile.conf**? Sounds like a great idea!

**Comment by philmmanjaro** [comment]
We will see, some like that.

**Comment by oberon2007** [comment]
It's maybe just not ideal to export an explicit preferred browser system-wide... Will it not be a problem when you later want to changes the default on user level?

**Comment by philmmanjaro** [comment]
Yep, that is why we used xdg-open for that. The question is why you have a loop in i3 and openbox.

**Comment by oberon2007** [comment]
The reason is this:
https://wiki.archlinux.org/index.php/Xdg-open
> Inside a desktop environment (like GNOME, KDE, or Xfce), xdg-open simply passes the arguments to those desktop environment's file-opener application (eg. gvfs-open, kde-open, or exo-open). which means that the associations are left up to the desktop environment.
> When no desktop environment is detected (for example when one runs a standalone window manager like eg. Openbox), xdg-open will use its own configuration files.

**Comment by oberon2007** [comment]
Anyway, I'd say it's a bug of xdg-open ...

**Comment by Chrysostomus** [comment]
Yeah, a well known bug at that. I think that is why arch wiki lists so many xdg-open alternatives, which advertise themselves as working properly without desktop enviroment. 

We could file a bug upstream (with a possible pull request for fix), or we could just use one of the alternative drop in replacements in standalone wm profiles.

**Comment by oberon2007** [comment]
Do you have experiences with any of the alternatives?

**Comment by Chrysostomus** [comment]
Not yet much. Needs some further experimenting. Linopen was unsuitable in my opinion. Busking seemed promising, but I haven't tested it yet. Arch wiki seems recommend xdg-utils-mimeo and mimeo. They are developed by xyne for this very purpose, so they should work, but they also require python2.

**Comment by Chrysostomus** [comment]
Oky. .. b.      .v ä.    Nwbvvv .         E. E e e.. .  ;;b;  n2 nbbbuån. Kå0

**Comment by Chrysostomus** [comment]
... that was my one year old daughter, sorry about that.

**Comment by philmmanjaro** [comment]
Ok, in this case we should disable xdg-open for these editions like you already did and find a proper solution for it. Are there any other editons needed this workaround?

**Comment by Chrysostomus** [comment]
Bspwm edition. It already sets BROWSER, no need to fiddle with that.

**Comment by philmmanjaro** [comment]
How did you "fix" it there?

**Comment by oberon2007** [comment]
It looks to me now that overriding BROWSER at user level seems to be sufficient to prevent the loop issue. Doesn't give us a xdg-open functionality of course, but in that case for now we could just leave the livecd-script as it is.

**Comment by Chrysostomus** [comment]
@philmmanjaro: I exported $BROWSER from .profile and .dmenurc. Seemed to work. 

If it can be overridden at user levwl, all is well. And if some standalone wm editions really needs xdg-open, there is always the mimeo route?

**Comment by philmmanjaro** [comment]
Ok, then we close it then ...

**Pull request closed without merging**
