### PR TITLE
Move build server to https

### PR DESCRIPTION
**Pull request by Ste74**

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Currently we don't use **master**. Please port it to [stable-0.15.x branch](https://github.com/manjaro/manjaro-tools/tree/stable-0.15.x).

**Comment by Ste74** [comment]
Opss.. sorry you are right, my fault .. Tonight at home move all .. If you trust, you could give me access :p  ;)

**Comment by philmmanjaro** [comment]
Ok, added you to needed support group.

**Comment by Ste74** [comment]
Thank you :smile:

**Pull request closed without merging**
